import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(`${geistSans.variable} ${geistMono.variable} antialiased`, "relative flex size-full min-h-screen flex-col bg-slate-50 group/design-root overflow-x-hidden")}
        style={{ fontFamily: "Plus Jakarta Sans, Noto Sans, sans-serif" }}
      >
        <Navbar />
        <main className="layout-container h-full w-full grow lg:px-48 justify-center flex flex-col flex-1 py-8 space-y-16">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
